# Generated by Django 4.1.4 on 2022-12-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('date', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('relative_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TotalReturnsIndex_Data',
            fields=[
                ('date', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nifty_smallcap_tri', models.FloatField()),
                ('nifty_50_tri', models.FloatField()),
                ('relative_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('subscription_option', models.IntegerField(default=1)),
                ('sip_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('current_sip_amount', models.FloatField()),
                ('step_up_percentage', models.FloatField()),
                ('step_up_month', models.IntegerField()),
                ('subscription_option', models.IntegerField(default=1)),
                ('last_updated_date', models.DateField()),
                ('next_step_up_date', models.DateField()),
            ],
        ),
    ]
